Fix for jodatime IllegalInstantException: Cannot parse.. Illegal instant due to time zone offset transition
org.joda.time.IllegalInstantException: Cannot parse "2023-09-03": Illegal instant due to time zone offset transition (America/Santiago)
	org.joda.time.format.DateTimeParserBucket.computeMillis(SourceFile:390)
	org.joda.time.format.DateTimeFormatter.parseMillis(SourceFile:749)
	org.joda.time.convert.StringConverter.getInstantMillis(SourceFile:65)
	org.joda.time.base.BaseDateTime.<init>(SourceFile:171)
	org.joda.time.DateTime.<init>(SourceFile:241)
	com.urbandroid.sleep.addon.stats.model.socialjetlag.SleepRegularityIndexUtil.extractSRIScores(SourceFile:172)