Update SleepRegularityIndexUtil.java
It seems Joda DateTime has an issue with gaps for non existent dates caused by day light saving etc.. 

See
https://stackoverflow.com/questions/5451152/how-to-handle-jodatime-illegal-instant-due-to-time-zone-offset-transition

So I have migrated DateTime to use LocalDate instead and set the tiemzone to UTC otherwise we see crashes fro various timezones. Hope this does not break something in the calculation?

org.joda.time.IllegalInstantException: Cannot parse "2022-10-16": Illegal instant due to time zone offset transition (America/Sao_Paulo)
	org.joda.time.format.DateTimeParserBucket.computeMillis(SourceFile:390)
	org.joda.time.format.DateTimeFormatter.parseDateTime(SourceFile:856)
	org.joda.time.DateTime.parse(SourceFile:144)